'''
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

def get_number(n):
    '''
    n is the number of divisors we are looking for.
    Runs exponentially on values of n.
    See http://code.jasonbhill.com/sage/project-euler-problem-12/
    For mathematical solution & example code
    '''
    i = 1
    tri_num = 0
    found = False

    while not found:

        tri_num += i
        divisors = 0

        for x in range(1, tri_num+1):
            if tri_num % x == 0:
                divisors += 1
        if divisors > n:
            found = True
            return tri_num

        i += 1
